#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables

if yad --skip-taskbar --fixed --center --text-align=fill --borders=6 --title="NOTIFICACION" --text="Este programa le permitira borrar de forma segura toda la informacion de un dispositivo externo. Para borrar el disco duro local utilice el script DESTRUIR"; then
	borrar=$(fdisk -l | grep "Disco" | sed '/zram/d' | sed '/loop/d' | awk '{print $2}' | sed 's/.$//g' | yad --center --no-click --list --title="Lista de dispositivos" --text="Seleccione el dispositivo que desea borrar." --separator="" --column 'Dispositivo' --height 380 --width 150 --button="ACEPTAR":0)

	if [[ -z "$borrar" ]]; then
		yad --center --window-icon=error --title=Error --button="Ir atras":0 --button="Salir":1 --text="No selecciono nada. Debe escoger un dispositivo."
		if [[ $? = 0 ]]; then
			source $0
		else
			rm -f /run/$(basename $0).pid
			exit 1
		fi
	fi

	function borrar_1 () {
		cat /dev/zero > "$borrar"
		cat /dev/urandom > "$borrar"
		shred -fz -n 5 "$borrar"
}

	function borrar_2 () {
		cat /dev/zero > "$borrar"
		cat /dev/urandom > "$borrar"
}

	function borrar_3 () {
		cat /dev/zero > "$borrar"
}

	function mensaje () {
		$final --text="Borrado finalizado."
}

	function terminando () {
		rm -f /run/$(basename $0).pid
		exit 1
}

	modo=$(yad --sticky --fixed --center --width=360 --height=450 --window-icon=/usr/share/icons/post-install.png --text="Seleccione el modo de borrado para el dispositivo" --no-click --list --title="Tipo de borrado" --column=Acciones "Seguro: zero, urandom, shred" "Medio: zero, urandom" "Rapido: zero")

	if [ "$modo" = "Seguro: zero, urandom, shred|" ]; then
		yad --center --window-icon=error --title=Advertencia --button="Continuar":0 --button="Salir":1 --text="¿Esta seguro de continuar? Esta operacion no podra revertirse."
		if [[ $? = 0 ]]; then
			borrar_1 | $progreso --title="Borrando" --progress-text="Borrando el disco, esto proceso puede tomar varias horas, por favor espere."
			mensaje
		else
			terminando
		fi

	elif [ "$modo" = "Medio: zero, urandom|" ]; then
		yad --center --window-icon=error --title=Advertencia --button="Continuar":0 --button="Salir":1 --text="¿Esta seguro de continuar? Esta operacion no podra revertirse."
		if [[ $? = 0 ]]; then
			borrar_2 | $progreso --title="Borrando" --progress-text="Borrando el disco, esto proceso puede tomar varias horas, por favor espere."
			mensaje
		else
			terminando
		fi	

	elif [ "$modo" = "Rapido: zero|" ]; then
		yad --center --window-icon=error --title=Advertencia --button="Continuar":0 --button="Salir":1 --text="¿Esta seguro de continuar? Esta operacion no podra revertirse."
		if [[ $? = 0 ]]; then
			borrar_3 | $progreso --title="Borrando" --progress-text="Borrando el disco, esto proceso puede tomar varias horas, por favor espere."
			mensaje
		else
			terminando
		fi

	else
		echo 1 > /dev/null
	fi
else
	echo 1 > /dev/null
fi
rm -f /run/$(basename $0).pid
exit 0
